### ISSUE TITLE
Trakt TV Show Collection unable to get into any show

### ISSUE THREAD

**Issue by zemely** [team-crew/team-crew.github.io#184]
So, I got Trakt authorized probably 4-5 times. Movies Watchlist works fine but the Trakt TV Shows collection, while lists all my TV Shows collection, will not let get inside any TV Show no matter what. All other addons work fine. Repo version 0.3.7., addon version 2.0.6, KODI 2.1, Android ONN 4K box. About a week ago all was working fine on another Android box. Any idea?

**Comment by Martinkingdom** [comment]
I struggled to up load daddy live on my Lodi.

**Comment by ononotu** [comment]
I have set up The Crew repository on KODI, and I authorized my Trakt account.  I got the message that my device had been authorized.  But when I click on “My TV Shows”, I get any error message that says “No Trakt Account Found”  What am I doing wrong or what additional step do I need to take to see my collection?

**Comment by Khub20** [comment]
You should be working in Add-ons. Everything you setup should go thru My add ons.forget the other links

**Comment by ononotu** [comment]
I used add-ons. Went through the KODI Add-on repository, went to Program add-ons, and installed Trakt from there. I then went through the activation process and got the Trakt installed notification, but I still get the "no account found" when trying to pull up my TV shows or my movies.Also, I am able to log into my Trakt account online, and it is intact.Is there a bug that needs fixing?Sent from my Galaxy
-------- Original message --------From: Khub20 ***@***.***> Date: 3/13/25  5:28 PM  (GMT-06:00) To: "team-crew/team-crew.github.io" ***@***.***> Cc: ononotu ***@***.***>, Comment ***@***.***> Subject: Re: [team-crew/team-crew.github.io] Trakt TV Show Collection unable to get into any show (Issue #184) 
  You should be working in Add-ons. Everything you setup should go thru My add ons.forget the other links—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



Khub20 left a comment (team-crew/team-crew.github.io#184)
You should be working in Add-ons. Everything you setup should go thru My add ons.forget the other links

**Comment by ononotu** [comment]
Could one or more of the dependencies that trakt needs be corrupt?I tried deleting trakt and reloading it, but I got the same error message.HELP!Sent from my Galaxy
-------- Original message --------From: Khub20 ***@***.***> Date: 3/13/25  5:28 PM  (GMT-06:00) To: "team-crew/team-crew.github.io" ***@***.***> Cc: ononotu ***@***.***>, Comment ***@***.***> Subject: Re: [team-crew/team-crew.github.io] Trakt TV Show Collection unable to get into any show (Issue #184) 
  You should be working in Add-ons. Everything you setup should go thru My add ons.forget the other links—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



Khub20 left a comment (team-crew/team-crew.github.io#184)
You should be working in Add-ons. Everything you setup should go thru My add ons.forget the other links

**Comment by ononotu** [comment]
Here is my setup:

 

KODI:  Omega v. 21.2

Repository:  The Crew

 

Why am I getting “No Account Found” error message when I try to get into My Movies or My TV Shows?  Is KODI Omega v.21.2 Add-Ons the problem, or is it The Crew repository that can’t sync with Trakt? It has only been since I upgraded to KODI Omega 21.2 that I have had this issue with Trakt. I have been using The Crew the whole time.

**Comment by thecrewwh** [comment]
Yes it is a bug it is fixed in the beta and upcoming version

**Comment by ononotu** [comment]
How do I clear the check marks on the posters on the wall?Sent from my Galaxy
-------- Original message --------From: thecrewwh ***@***.***> Date: 8/25/25  4:00 PM  (GMT-06:00) To: "team-crew/team-crew.github.io" ***@***.***> Cc: ononotu ***@***.***>, Comment ***@***.***> Subject: Re: [team-crew/team-crew.github.io] Trakt TV Show Collection unable to get into any show (Issue #184) thecrewwh left a comment (team-crew/team-crew.github.io#184)
Yes it is a bug it is fixed in the beta and upcoming version
